<?php

namespace WorkflowBundle\Repository;

/**
 * WorkflowStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowStepRepository extends \Doctrine\ORM\EntityRepository
{
}
