?php

namespace AppBundle\Repository;

/**
 * ApprobationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprobationRepository extends \Doctrine\ORM\EntityRepository
{
}
