<?php

namespace AppBundle\Repository;

/**
 * Bon_livraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bon_livraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
