<?php

namespace AppBundle\Repository;

/**
 * CentrecoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentrecoutRepository extends \Doctrine\ORM\EntityRepository
{
}
