<?php

namespace AppBundle\Repository;

/**
 * EtiquettesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtiquettesRepository extends \Doctrine\ORM\EntityRepository
{
}
