get_mail_fact:
    resource: "@getMailFactBundle/Resources/config/routing.yml"
    prefix:   /getmailfact

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_annotation:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

user_annotation:
    resource: "@UserBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_admin:
    resource: routing_admin.yml
    prefix:   /%base_url_admin%

_front:
    resource: routing_front.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#cms: # a commenter si pas CMS
#    resource: "@CmsBundle/Controller/"
#    type:     annotation
#    prefix:   /
