<?php

namespace getMailFactBundle\Repository;

/**
 * StatusOfFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusOfFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
